#pragma once
#include "wled.h"

/*
 * Entirety of this file was generated by AI, including this comment.
 *
 * Mirror Chase Effect Usermod
 *
 * Creates a mirrored chase pattern from a user-defined center point.
 * Pattern flows outward (or inward) from center in both directions.
 *
 * Key feature: No wrapping artifacts in the chase pattern itself -
 * treats the strip as linear, not circular. Colors at equidistant
 * positions from center are always synchronized.
 */

class UsermodMirrorChase : public Usermod {

  private:
    bool initDone = false;
    static const char _name[];
    static const char _data_fx[];

  public:

    void setup() override;
    void loop() override;

    uint16_t getId() override {
      return USERMOD_ID_MIRROR_CHASE;
    }
};
